//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJCP.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CmdLineStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CmdLineStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RJCP.Core.Resources.CmdLineStrings", typeof(CmdLineStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptionArgumentsAttribute assigned to multiple fields/properties.
        /// </summary>
        internal static string ArgException_AssignedMultipleTimes {
            get {
                return ResourceManager.GetString("ArgException_AssignedMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection &apos;{0}&apos; must contain a primitive type.
        /// </summary>
        internal static string ArgException_CollectionNotPrimitive {
            get {
                return ResourceManager.GetString("ArgException_CollectionNotPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must be a primitive type.
        /// </summary>
        internal static string ArgException_FieldNotPrimitive {
            get {
                return ResourceManager.GetString("ArgException_FieldNotPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptionArgumentsAttribute collection must be type of string.
        /// </summary>
        internal static string ArgException_GenTypeString {
            get {
                return ResourceManager.GetString("ArgException_GenTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a value to an option that is not a collection.
        /// </summary>
        internal static string ArgException_InvalidCollection {
            get {
                return ResourceManager.GetString("ArgException_InvalidCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection identified without an Add method.
        /// </summary>
        internal static string ArgException_InvalidCollectionNoAdd {
            get {
                return ResourceManager.GetString("ArgException_InvalidCollectionNoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected only one Generic parameter type argument.
        /// </summary>
        internal static string ArgException_InvalidTypeMultipleGenTypeParams {
            get {
                return ResourceManager.GetString("ArgException_InvalidTypeMultipleGenTypeParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member must be a concrete type, not a generic type definition.
        /// </summary>
        internal static string ArgException_InvalidTypeNoGeneric {
            get {
                return ResourceManager.GetString("ArgException_InvalidTypeNoGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a property or field.
        /// </summary>
        internal static string ArgException_NotPropertyOrField {
            get {
                return ResourceManager.GetString("ArgException_NotPropertyOrField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a non-writable property &apos;{0}&apos;.
        /// </summary>
        internal static string ArgException_NotSettableProperty {
            get {
                return ResourceManager.GetString("ArgException_NotSettableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; was specified multiple times.
        /// </summary>
        internal static string ArgException_OptionMultipleTimesSpecified {
            get {
                return ResourceManager.GetString("ArgException_OptionMultipleTimesSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; must be a primitive type.
        /// </summary>
        internal static string ArgException_PropertyNotPrimitive {
            get {
                return ResourceManager.GetString("ArgException_PropertyNotPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a readonly field &apos;{0}&apos;.
        /// </summary>
        internal static string ArgException_ReadOnlyField {
            get {
                return ResourceManager.GetString("ArgException_ReadOnlyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptionArgumentsAttribute must be assigned to a collection.
        /// </summary>
        internal static string ArgException_RequiresCollection {
            get {
                return ResourceManager.GetString("ArgException_RequiresCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing option &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorParsingOption {
            get {
                return ResourceManager.GetString("ErrorParsingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong format &apos;{0}&apos; given to option &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorParsingOptionFormat {
            get {
                return ResourceManager.GetString("ErrorParsingOptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error: Setting an option to false, when it&apos;s already set.
        /// </summary>
        internal static string InternalError_OptionIsAlreadySet {
            get {
                return ResourceManager.GetString("InternalError_OptionIsAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data after quoted list, expect &apos;{0}&apos; only.
        /// </summary>
        internal static string ListInvalidData {
            get {
                return ResourceManager.GetString("ListInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing quote in list.
        /// </summary>
        internal static string ListMissingQuote {
            get {
                return ResourceManager.GetString("ListMissingQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long option has invalid character: &apos;{0}&apos;.
        /// </summary>
        internal static string LongOptionInvalidChar {
            get {
                return ResourceManager.GetString("LongOptionInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Option may not be empty.
        /// </summary>
        internal static string LongOptionMayNotBeEmpty {
            get {
                return ResourceManager.GetString("LongOptionMayNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; has incorrect format.
        /// </summary>
        internal static string OptionIncorrectFormat {
            get {
                return ResourceManager.GetString("OptionIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; missing argument.
        /// </summary>
        internal static string OptionMissingArgument {
            get {
                return ResourceManager.GetString("OptionMissingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; expected but not provided.
        /// </summary>
        internal static string OptionMissingOption {
            get {
                return ResourceManager.GetString("OptionMissingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; provided multiple times.
        /// </summary>
        internal static string OptionMultipleTimes {
            get {
                return ResourceManager.GetString("OptionMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Options Style.
        /// </summary>
        internal static string OptionsStyleUnknown {
            get {
                return ResourceManager.GetString("OptionsStyleUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; not recognized.
        /// </summary>
        internal static string OptionUnknown {
            get {
                return ResourceManager.GetString("OptionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short option &apos;{0}&apos; character not allowed.
        /// </summary>
        internal static string ShortOptionInvalidChar {
            get {
                return ResourceManager.GetString("ShortOptionInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanging indent exceeds left boundary of indent.
        /// </summary>
        internal static string TerminalHangArgOutOfRange {
            get {
                return ResourceManager.GetString("TerminalHangArgOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent must be positive.
        /// </summary>
        internal static string TerminalIndentArgOutOfRange {
            get {
                return ResourceManager.GetString("TerminalIndentArgOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error, unknown token type.
        /// </summary>
        internal static string TerminalParseError {
            get {
                return ResourceManager.GetString("TerminalParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal height must be one line or greater.
        /// </summary>
        internal static string TerminalVirtualHeightRange {
            get {
                return ResourceManager.GetString("TerminalVirtualHeightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal width must be one character or greater.
        /// </summary>
        internal static string TerminalVirtualWidthRange {
            get {
                return ResourceManager.GetString("TerminalVirtualWidthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected option &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedOptionNonZeroGeneralArgs {
            get {
                return ResourceManager.GetString("UnexpectedOptionNonZeroGeneralArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected option &apos;{0}&apos; found, perhaps too many arguments after &apos;{1}&apos;.
        /// </summary>
        internal static string UnexpectedOptionNonZeroGeneralArgsLastToken {
            get {
                return ResourceManager.GetString("UnexpectedOptionNonZeroGeneralArgsLastToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected value for option &apos;{0}&apos;.
        /// </summary>
        internal static string UnexpectedValueForOption {
            get {
                return ResourceManager.GetString("UnexpectedValueForOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected value for option &apos;{0}&apos; (argument &apos;{1}&apos;).
        /// </summary>
        internal static string UnexpectedValueForOptionLastToken {
            get {
                return ResourceManager.GetString("UnexpectedValueForOptionLastToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line option {0} invalid, key value pairs must be isolated.
        /// </summary>
        internal static string UnixCmdLineToken {
            get {
                return ResourceManager.GetString("UnixCmdLineToken", resourceCulture);
            }
        }
    }
}
